// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"net/http"
	"pokemon-list/app"
	"pokemon-list/controller"
	"pokemon-list/repository"
	"pokemon-list/services"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	db := app.NewDB()
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	echo := app.NewRouter(userController)
	server := app.NewServer(echo)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, services.NewUserService, controller.NewUserController)
