// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/google/wire"
	"net/http"
	"pokemon-list/app"
	"pokemon-list/controller"
	"pokemon-list/repository"
	"pokemon-list/services"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	db := app.NewDB()
	userRepository := repository.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userController := controller.NewUserController(userService)
	myPokemonRepository := repository.NewMyPokemonRepository(db)
	myPokemonService := services.NewMyPokemonService(myPokemonRepository)
	myPokemonController := controller.NewMyPokemonController(myPokemonService)
	echo := app.NewRouter(userController, myPokemonController)
	server := app.NewServer(echo)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, services.NewUserService, controller.NewUserController)

var myPokemonSet = wire.NewSet(repository.NewMyPokemonRepository, services.NewMyPokemonService, controller.NewMyPokemonController)
